pipeline{
    agent any
    environment {
        DOCKER_IMAGE = "hello_world"
    }

    stages {
        stage('Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}", ".")
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    docker.image("${DOCKER_IMAGE}").inside {
                        sh 'Echo running inside Docker Container'
                    }
                }
            }

        }
    }

    post {
        success {
            echo 'pipeline excuted successfully!'
        }
        failure {
            echo 'Pipleline failed. Check logs.'
        }
        always {
            cleanWs()
            script {
                try {
                    docker.image("${DOCKER_IMAGE}").remove()
                } catch (Exception e) {
                    echo "Error removing Docker image: ${e.message}"
                }
            }
        }
    }

}